name: Build AppImage

on:
  push:
    branches:
      - master
      - appimage
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libglfw3-dev libassimp-dev catch2 nlohmann-json3-dev libglm-dev libpugixml-dev ninja-build pkg-config libgtk-3-dev libboost-all-dev libzip-dev libssl-dev libhdf5-dev libbz2-dev liblzma-dev zlib1g-dev libvulkan-dev glslang-tools libgtkmm-3.0-dev python3 python3-dev python3-numpy

      - name: Create build directory
        run: mkdir -p build

      - name: Make script executable
        run: chmod +x build-appimage.sh

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/cmake-build-release/appdir/usr \
            -DCMRC_ENABLE_INSTALL=OFF

      - name: Build AppImage
        run: ./build-appimage.sh build

      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Neoneuron.AppImage
          path: ./Neoneuron-*.AppImage
