name: Build AppImage

on:
  push:
    branches:
      - master
      - appimage
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
                    sudo apt update
          sudo apt install -y \
            cmake ninja-build pkg-config \
            libgtk-3-dev \
            libboost-all-dev \
            libzip-dev \
            libssl-dev \
            libhdf5-dev \
            libbz2-dev \
            liblzma-dev \
            zlib1g-dev \
            libvulkan-dev glslang-tools \
            python3 python3-dev python3-numpy

      - name: Create build directory
        run: mkdir -p build

      - name: Make script executable
        run: chmod +x build-appimage.sh

      - name: Build AppImage
        run: ./build-appimage.sh build

      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Neoneuron.AppImage
          path: ./Neoneuron-*.AppImage
